/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/model`; params?: Router.UnknownInputParams; } | { pathname: `/Navigation`; params?: Router.UnknownInputParams; } | { pathname: `/products`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/ssp`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/login-singup/login`; params?: Router.UnknownInputParams; } | { pathname: `/login-singup/signup`; params?: Router.UnknownInputParams; } | { pathname: `/profile-page/cart`; params?: Router.UnknownInputParams; } | { pathname: `/profile-page/check-out`; params?: Router.UnknownInputParams; } | { pathname: `/profile-page/dog-breed-detail`; params?: Router.UnknownInputParams; } | { pathname: `/profile-page/product-detail`; params?: Router.UnknownInputParams; } | { pathname: `/profile-page/wallet`; params?: Router.UnknownInputParams; } | { pathname: `/profile-page/wishlist`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/home`; params?: Router.UnknownOutputParams; } | { pathname: `/model`; params?: Router.UnknownOutputParams; } | { pathname: `/Navigation`; params?: Router.UnknownOutputParams; } | { pathname: `/products`; params?: Router.UnknownOutputParams; } | { pathname: `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/ssp`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/login-singup/login`; params?: Router.UnknownOutputParams; } | { pathname: `/login-singup/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/profile-page/cart`; params?: Router.UnknownOutputParams; } | { pathname: `/profile-page/check-out`; params?: Router.UnknownOutputParams; } | { pathname: `/profile-page/dog-breed-detail`; params?: Router.UnknownOutputParams; } | { pathname: `/profile-page/product-detail`; params?: Router.UnknownOutputParams; } | { pathname: `/profile-page/wallet`; params?: Router.UnknownOutputParams; } | { pathname: `/profile-page/wishlist`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/home${`?${string}` | `#${string}` | ''}` | `/model${`?${string}` | `#${string}` | ''}` | `/Navigation${`?${string}` | `#${string}` | ''}` | `/products${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/ssp${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/login-singup/login${`?${string}` | `#${string}` | ''}` | `/login-singup/signup${`?${string}` | `#${string}` | ''}` | `/profile-page/cart${`?${string}` | `#${string}` | ''}` | `/profile-page/check-out${`?${string}` | `#${string}` | ''}` | `/profile-page/dog-breed-detail${`?${string}` | `#${string}` | ''}` | `/profile-page/product-detail${`?${string}` | `#${string}` | ''}` | `/profile-page/wallet${`?${string}` | `#${string}` | ''}` | `/profile-page/wishlist${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/model`; params?: Router.UnknownInputParams; } | { pathname: `/Navigation`; params?: Router.UnknownInputParams; } | { pathname: `/products`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/ssp`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/login-singup/login`; params?: Router.UnknownInputParams; } | { pathname: `/login-singup/signup`; params?: Router.UnknownInputParams; } | { pathname: `/profile-page/cart`; params?: Router.UnknownInputParams; } | { pathname: `/profile-page/check-out`; params?: Router.UnknownInputParams; } | { pathname: `/profile-page/dog-breed-detail`; params?: Router.UnknownInputParams; } | { pathname: `/profile-page/product-detail`; params?: Router.UnknownInputParams; } | { pathname: `/profile-page/wallet`; params?: Router.UnknownInputParams; } | { pathname: `/profile-page/wishlist`; params?: Router.UnknownInputParams; };
    }
  }
}
